### ISSUE TITLE
Prevent = from being added if it is a comment in .env

### ISSUE THREAD

**Issue by mbalandis** [dongido001/vscode-sync-env#2]
In .env when I add `#` it adds `#=`

I would like to add something like this: `########## MAIN CONFIG ############`

without it doing `########## MAIN CONFIG ############=` in .env.example

**Comment by dongido001** [comment]
Thanks for filling the issue, I will look into it.

**Comment by dongido001** [comment]
This is fixed and should appear in next release

**Comment by dongido001** [comment]
Available now on version 1.0.4

**Comment by NicolasPL64** [comment]
@dongido001 I just leaked my DB connection string because of this.
I commented out my `DATABASE_URL="string"` and in the `.env.example` it turned my `DATABASE_URL` into `#DATABASE_URL="string"`, thus getting my DB connection string leaked without my knowledge.
It'd be neat to get the comments ignored if they contain an `=` symbol.
